#!/usr/bin/env node
// Regenerates src/idl.ts from src/idl/solsocket_engine.json.
// Run after `anchor build` changes the IDL:  npm run gen:idl
// The IDL is embedded as a TS module (instead of a JSON import) so the ESM
// build stays loadable by native Node, which rejects bare JSON imports.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkg = dirname(dirname(fileURLToPath(import.meta.url)));
const idl = JSON.parse(readFileSync(join(pkg, "src/idl/solsocket_engine.json"), "utf8"));

const out = `// Generated by scripts/embed-idl.mjs from src/idl/solsocket_engine.json — do not edit.
export const IDL = ${JSON.stringify(idl, null, 2)} as const;
`;
writeFileSync(join(pkg, "src/idl.ts"), out);
console.log("wrote src/idl.ts");
